// TilingKey模板定义的头文件
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define BTS_SCENE_AIV 0
#define BTS_SCENE_CASE6_AIC 1
#define BTS_SCENE_CASE7_AIC 2
#define BTS_SCENE_CASE3_AIV 3
#define BTS_SCENE_CASE4_AIV 4
#define BTS_SCENE_CASE4_AIC 5
#define BTS_SCENE_CASE1_AIV 6
#define BTS_SCENE_CASE2_AIV 7
#define BTS_SCENE_CASE10_AIC 8
#define BTS_SCENE_CASE10_AIV 9
#define BTS_SCENE_CASE9_AIC 10
#define BTS_SCENE_CASE9_AIV 11
#define BTS_SCENE_CASE3_AIC 12

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_FORMAT_DECL(
        BTS_SCENE,
        BTS_SCENE_AIV,
        BTS_SCENE_CASE6_AIC,
        BTS_SCENE_CASE7_AIC,
        BTS_SCENE_CASE3_AIV,
        BTS_SCENE_CASE4_AIV,
        BTS_SCENE_CASE4_AIC,
        BTS_SCENE_CASE1_AIV,
        BTS_SCENE_CASE2_AIV,
        BTS_SCENE_CASE10_AIC,
        BTS_SCENE_CASE10_AIV,
        BTS_SCENE_CASE9_AIC,
        BTS_SCENE_CASE9_AIV,
        BTS_SCENE_CASE3_AIC),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE6_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE7_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE3_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE3_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE4_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE4_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE1_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE2_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE10_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE10_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE9_AIC),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_FORMAT_SEL(BTS_SCENE, BTS_SCENE_CASE9_AIV),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
    ),
);
