/*!
 * \file chunk_scaled_dot_kkt_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __CHUNKSCALEDDOTKKT_TILING_KEY_H__
#define __CHUNKSCALEDDOTKKT_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_0 0
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_1 1
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_2 2
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_3 3
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_4 4
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_5 5
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_6 6
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_7 7
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_8 8
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_9 9
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_10 10
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_11 11
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_12 12
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_13 13
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_14 14
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_15 15
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_16 16
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_17 17
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_18 18
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_19 19
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_20 20
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_22 22
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_24 24
#define CHUNKSCALEDDOTKKT_TPL_SCH_MODE_28 28

ASCENDC_TPL_ARGS_DECL(
    ChunkScaledDotKkt,
    ASCENDC_TPL_UINT_DECL(schMode, 5, ASCENDC_TPL_UI_LIST,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_0, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_1,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_2, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_3,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_4, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_5,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_6, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_7,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_8, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_9,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_10, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_11,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_12, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_13,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_14, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_15,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_16, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_17,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_18, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_19,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_20, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_22,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_24, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_28));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_0, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_1,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_2, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_3,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_4, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_5,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_6, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_7,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_8, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_9,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_10, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_11,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_12, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_13,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_14, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_15,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_16, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_17,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_18, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_19,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_20, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_22,
        CHUNKSCALEDDOTKKT_TPL_SCH_MODE_24, CHUNKSCALEDDOTKKT_TPL_SCH_MODE_28)));

#endif
