// TilingKey template definitions for BatchToSpace.
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_BOOL_DECL(TUNING, 0, 1),
    ASCENDC_TPL_UINT_DECL(STATIC_VARIANT, ASCENDC_TPL_4_BW,
                         ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_BOOL_SEL(TUNING, 0),
        ASCENDC_TPL_UINT_SEL(STATIC_VARIANT, ASCENDC_TPL_UI_LIST, 0, 5, 6, 7, 8, 9, 10),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_BOOL_SEL(TUNING, 1),
        ASCENDC_TPL_UINT_SEL(STATIC_VARIANT, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_BOOL_SEL(TUNING, 0),
        ASCENDC_TPL_UINT_SEL(STATIC_VARIANT, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_BOOL_SEL(TUNING, 1),
        ASCENDC_TPL_UINT_SEL(STATIC_VARIANT, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3),
    ),
);
