/*!
 * \file inplace_update_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __INPLACEUPDATE_TILING_KEY_H__
#define __INPLACEUPDATE_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define INPLACEUPDATE_TPL_SCH_MODE_0 0
#define INPLACEUPDATE_TPL_SCH_MODE_1 1
#define INPLACEUPDATE_TPL_SCH_MODE_2 2
#define INPLACEUPDATE_TPL_SCH_MODE_3 3
#define INPLACEUPDATE_TPL_SCH_MODE_4 4
#define INPLACEUPDATE_TPL_SCH_MODE_5 5
#define INPLACEUPDATE_TPL_SCH_MODE_6 6
#define INPLACEUPDATE_TPL_SCH_MODE_7 7
#define INPLACEUPDATE_TPL_SCH_MODE_8 8
#define INPLACEUPDATE_TPL_SCH_MODE_9 9
#define INPLACEUPDATE_TPL_SCH_MODE_10 10
#define INPLACEUPDATE_TPL_SCH_MODE_11 11
#define INPLACEUPDATE_TPL_SCH_MODE_12 12
#define INPLACEUPDATE_TPL_SCH_MODE_13 13

ASCENDC_TPL_ARGS_DECL(
    InplaceUpdate,
    ASCENDC_TPL_UINT_DECL(schMode, 4, ASCENDC_TPL_UI_LIST, INPLACEUPDATE_TPL_SCH_MODE_0,
        INPLACEUPDATE_TPL_SCH_MODE_1, INPLACEUPDATE_TPL_SCH_MODE_2, INPLACEUPDATE_TPL_SCH_MODE_3,
        INPLACEUPDATE_TPL_SCH_MODE_4, INPLACEUPDATE_TPL_SCH_MODE_5, INPLACEUPDATE_TPL_SCH_MODE_6,
        INPLACEUPDATE_TPL_SCH_MODE_7, INPLACEUPDATE_TPL_SCH_MODE_8, INPLACEUPDATE_TPL_SCH_MODE_9,
        INPLACEUPDATE_TPL_SCH_MODE_10, INPLACEUPDATE_TPL_SCH_MODE_11, INPLACEUPDATE_TPL_SCH_MODE_12,
        INPLACEUPDATE_TPL_SCH_MODE_13));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, INPLACEUPDATE_TPL_SCH_MODE_0,
        INPLACEUPDATE_TPL_SCH_MODE_1, INPLACEUPDATE_TPL_SCH_MODE_2, INPLACEUPDATE_TPL_SCH_MODE_3,
        INPLACEUPDATE_TPL_SCH_MODE_4, INPLACEUPDATE_TPL_SCH_MODE_5, INPLACEUPDATE_TPL_SCH_MODE_6,
        INPLACEUPDATE_TPL_SCH_MODE_7, INPLACEUPDATE_TPL_SCH_MODE_8, INPLACEUPDATE_TPL_SCH_MODE_9,
        INPLACEUPDATE_TPL_SCH_MODE_10, INPLACEUPDATE_TPL_SCH_MODE_11, INPLACEUPDATE_TPL_SCH_MODE_12,
        INPLACEUPDATE_TPL_SCH_MODE_13)));

#endif
