/*!
 * \file quant_batch_mat_mul_v3_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __QUANTBATCHMATMULV3_TILING_KEY_H__
#define __QUANTBATCHMATMULV3_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define QUANTBATCHMATMULV3_TPL_SCH_MODE_0 0
#define QUANTBATCHMATMULV3_TPL_SCH_MODE_1 1
#define QUANTBATCHMATMULV3_TPL_SCH_MODE_2 2
#define QUANTBATCHMATMULV3_TPL_SCH_MODE_3 3
#define QUANTBATCHMATMULV3_TPL_SCH_MODE_4 4

ASCENDC_TPL_ARGS_DECL(
    QuantBatchMatMulV3,
    ASCENDC_TPL_UINT_DECL(schMode, 3, ASCENDC_TPL_UI_LIST, QUANTBATCHMATMULV3_TPL_SCH_MODE_0,
        QUANTBATCHMATMULV3_TPL_SCH_MODE_1, QUANTBATCHMATMULV3_TPL_SCH_MODE_2,
        QUANTBATCHMATMULV3_TPL_SCH_MODE_3, QUANTBATCHMATMULV3_TPL_SCH_MODE_4));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, QUANTBATCHMATMULV3_TPL_SCH_MODE_0,
        QUANTBATCHMATMULV3_TPL_SCH_MODE_1, QUANTBATCHMATMULV3_TPL_SCH_MODE_2,
        QUANTBATCHMATMULV3_TPL_SCH_MODE_3, QUANTBATCHMATMULV3_TPL_SCH_MODE_4)));

#endif
