// BatchToSpace tiling key template definition.
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(MODE_KEY, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_RANGE, 1, 9, 25)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(MODE_KEY, ASCENDC_TPL_UI_RANGE, 1, 13, 22)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(MODE_KEY, ASCENDC_TPL_UI_RANGE, 1, 9, 12)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(MODE_KEY, ASCENDC_TPL_UI_RANGE, 1, 23, 25)
    ),
);
