// TilingKey模板定义的头文件
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define ERF_TINY_LENGTH_THRESHOLD 128U

#define ERF_TINY_FIXED_LENGTH_1   1U
#define ERF_TINY_FIXED_LENGTH_2   2U
#define ERF_TINY_FIXED_LENGTH_3   3U
#define ERF_TINY_FIXED_LENGTH_4   4U
#define ERF_TINY_FIXED_LENGTH_8   8U
#define ERF_TINY_FIXED_LENGTH_16  16U
#define ERF_TINY_FIXED_LENGTH_32  32U
#define ERF_TINY_FIXED_LENGTH_64  64U
#define ERF_TINY_FIXED_LENGTH_128 128U
#define ERF_SPECIAL_LENGTH_371    371U
#define ERF_LARGE_SPECIAL_MIN_120K 120000U
#define ERF_LARGE_SPECIAL_MAX_140K 140000U

#define ERF_TPL_SCH_MODE_SMALL_4K 0
#define ERF_TPL_SCH_MODE_SMALL_8K 1
#define ERF_TPL_SCH_MODE_MID      2
#define ERF_TPL_SCH_MODE_LARGE    3
#define ERF_TPL_SCH_MODE_TINY     4
#define ERF_TPL_SCH_MODE_TINY_FIXED_8   5
#define ERF_TPL_SCH_MODE_TINY_FIXED_16  6
#define ERF_TPL_SCH_MODE_TINY_FIXED_32  7
#define ERF_TPL_SCH_MODE_TINY_FIXED_64  8
#define ERF_TPL_SCH_MODE_TINY_FIXED_128 9
#define ERF_TPL_SCH_MODE_TINY_PAD       10
#define ERF_TPL_SCH_MODE_SMALL_4K_PAD   11
#define ERF_TPL_SCH_MODE_SMALL_8K_PAD   12
#define ERF_TPL_SCH_MODE_TINY_FIXED_1   13
#define ERF_TPL_SCH_MODE_TINY_FIXED_2   14
#define ERF_TPL_SCH_MODE_TINY_FIXED_3   15
#define ERF_TPL_SCH_MODE_TINY_FIXED_4   16
#define ERF_TPL_SCH_MODE_FIXED_371_VECTOR 17
#define ERF_TPL_SCH_MODE_LARGE_120_140K_16CORE 18

ASCENDC_TPL_ARGS_DECL(Erf,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(schMode, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST,
        ERF_TPL_SCH_MODE_TINY_FIXED_1,
        ERF_TPL_SCH_MODE_TINY_FIXED_2,
        ERF_TPL_SCH_MODE_TINY_FIXED_3,
        ERF_TPL_SCH_MODE_TINY_FIXED_4,
        ERF_TPL_SCH_MODE_TINY_FIXED_8,
        ERF_TPL_SCH_MODE_TINY_FIXED_16,
        ERF_TPL_SCH_MODE_TINY_FIXED_32,
        ERF_TPL_SCH_MODE_TINY_FIXED_64,
        ERF_TPL_SCH_MODE_TINY_FIXED_128,
        ERF_TPL_SCH_MODE_TINY,
        ERF_TPL_SCH_MODE_TINY_PAD,
        ERF_TPL_SCH_MODE_SMALL_4K,
        ERF_TPL_SCH_MODE_SMALL_4K_PAD,
        ERF_TPL_SCH_MODE_SMALL_8K,
        ERF_TPL_SCH_MODE_SMALL_8K_PAD,
        ERF_TPL_SCH_MODE_MID,
        ERF_TPL_SCH_MODE_LARGE,
        ERF_TPL_SCH_MODE_FIXED_371_VECTOR,
        ERF_TPL_SCH_MODE_LARGE_120_140K_16CORE)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
            ERF_TPL_SCH_MODE_TINY_FIXED_1,
            ERF_TPL_SCH_MODE_TINY_FIXED_2,
            ERF_TPL_SCH_MODE_TINY_FIXED_3,
            ERF_TPL_SCH_MODE_TINY_FIXED_4,
            ERF_TPL_SCH_MODE_TINY_FIXED_8,
            ERF_TPL_SCH_MODE_TINY_FIXED_16,
            ERF_TPL_SCH_MODE_TINY_FIXED_32,
            ERF_TPL_SCH_MODE_TINY_FIXED_64,
            ERF_TPL_SCH_MODE_TINY_FIXED_128,
            ERF_TPL_SCH_MODE_TINY,
            ERF_TPL_SCH_MODE_TINY_PAD,
            ERF_TPL_SCH_MODE_SMALL_4K,
            ERF_TPL_SCH_MODE_SMALL_4K_PAD,
            ERF_TPL_SCH_MODE_SMALL_8K,
            ERF_TPL_SCH_MODE_SMALL_8K_PAD,
            ERF_TPL_SCH_MODE_MID,
            ERF_TPL_SCH_MODE_LARGE,
            ERF_TPL_SCH_MODE_FIXED_371_VECTOR,
            ERF_TPL_SCH_MODE_LARGE_120_140K_16CORE)
    ),
);
