
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define BATCH_TO_SPACE_MODE_GENERAL 0
#define BATCH_TO_SPACE_MODE_LANE_STRIDED_SCATTER_SAFE 1
#define BATCH_TO_SPACE_MODE_HIGH_DEPTH_CONTIG_PACK 2
#define BATCH_TO_SPACE_MODE_BS4_HIGH_DEPTH_CONTIG_PACK 4
#define BATCH_TO_SPACE_MODE_HIGH_DILATION_LANE_SCATTER 6
#define BATCH_TO_SPACE_MODE_LIGHTWEIGHT_GENERIC 3
#define BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK 7
#define BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_8 8
#define BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_16 9
#define BATCH_TO_SPACE_MODE_BLOCK1_CROP_ROW_CONTRACT 10
#define BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS2 11
#define BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS4 12
#define BATCH_TO_SPACE_MODE_BLOCK1_VERTICAL_CROP_CONTIG 13
#define BATCH_TO_SPACE_MODE_T4_BS2_MID_LANE_CONTRACT 14
#define BATCH_TO_SPACE_MODE_T7_C1_8X8_SMALLCROP_MC8 15
#define BATCH_TO_SPACE_MODE_T7_BS2_SMALLC_TINY_WIDE_OWNER 16
#define BATCH_TO_SPACE_MODE_T6_BS2_FP16_HIGHDEPTH_MEDIUM_ROW2 17
#define BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW 18
#define BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW_LANE 19
#define BATCH_TO_SPACE_MODE_T7_OUTW1_ALIGNED_ROWCONTRACT 20
#define BATCH_TO_SPACE_MODE_T7_OUTW2_ALIGNED_ROWCONTRACT 21
#define BATCH_TO_SPACE_MODE_T7_OUTW4_ALIGNED_ROWCONTRACT 22
#define BATCH_TO_SPACE_MODE_T7_OUTW7_ALIGNED_ROWCONTRACT 23

#define BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW1_DELAY 24
#define BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW2_DELAY 25
#define BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW3_4_DELAY 26
#define BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW5_7_DELAY 27
#define BATCH_TO_SPACE_MODE_T7_BUCKET_OTHER_DELAY 28

#define BATCH_TO_SPACE_MODE_T7_OTHER_B1_W3_4_ROW256_512_OUT64_128_DELAY 29
#define BATCH_TO_SPACE_MODE_T7_OTHER_B2_W3_4_ROW256_512_OUT128_512_DELAY 30
#define BATCH_TO_SPACE_MODE_T7_OTHER_B3_W3_4_ROW_GT512_DELAY 31
#define BATCH_TO_SPACE_MODE_T7_OTHER_B4_W5_7_ROW_GT256_DELAY 32
#define BATCH_TO_SPACE_MODE_T7_OTHER_B6_ROWNARROW_OUTW_GE8_DELAY 34
#define BATCH_TO_SPACE_MODE_T7_OTHER_B7_NONALIGNED_CGT16_DELAY 35
#define BATCH_TO_SPACE_MODE_T7_OTHER_B8_OTHER_DELAY 36
#define BATCH_TO_SPACE_MODE_T7_OTHER_B5_W1_2_ROW_GT128_PERF 38
#define BATCH_TO_SPACE_MODE_T9_BS4_ALIGNED_ROW_ASSEMBLE 39

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(MODE, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST,
        BATCH_TO_SPACE_MODE_GENERAL,
        BATCH_TO_SPACE_MODE_LANE_STRIDED_SCATTER_SAFE,
        BATCH_TO_SPACE_MODE_HIGH_DEPTH_CONTIG_PACK,
        BATCH_TO_SPACE_MODE_BS4_HIGH_DEPTH_CONTIG_PACK,
        BATCH_TO_SPACE_MODE_HIGH_DILATION_LANE_SCATTER,
        BATCH_TO_SPACE_MODE_LIGHTWEIGHT_GENERIC,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_8,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_16,
        BATCH_TO_SPACE_MODE_BLOCK1_CROP_ROW_CONTRACT,
        BATCH_TO_SPACE_MODE_BLOCK1_VERTICAL_CROP_CONTIG,
        BATCH_TO_SPACE_MODE_T4_BS2_MID_LANE_CONTRACT,
        BATCH_TO_SPACE_MODE_T7_C1_8X8_SMALLCROP_MC8,
        BATCH_TO_SPACE_MODE_T7_BS2_SMALLC_TINY_WIDE_OWNER,
        BATCH_TO_SPACE_MODE_T6_BS2_FP16_HIGHDEPTH_MEDIUM_ROW2,
        BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW,
        BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW_LANE,
        BATCH_TO_SPACE_MODE_T7_OUTW1_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW2_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW4_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW7_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW1_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW2_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW3_4_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW5_7_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OTHER_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B1_W3_4_ROW256_512_OUT64_128_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B2_W3_4_ROW256_512_OUT128_512_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B3_W3_4_ROW_GT512_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B4_W5_7_ROW_GT256_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B5_W1_2_ROW_GT128_PERF,
        BATCH_TO_SPACE_MODE_T9_BS4_ALIGNED_ROW_ASSEMBLE,
        BATCH_TO_SPACE_MODE_T7_OTHER_B6_ROWNARROW_OUTW_GE8_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B7_NONALIGNED_CGT16_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B8_OTHER_DELAY,
        BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS2,
        BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS4),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(MODE, ASCENDC_TPL_UI_LIST,
            BATCH_TO_SPACE_MODE_GENERAL,
            BATCH_TO_SPACE_MODE_LANE_STRIDED_SCATTER_SAFE,
            BATCH_TO_SPACE_MODE_HIGH_DEPTH_CONTIG_PACK,
            BATCH_TO_SPACE_MODE_BS4_HIGH_DEPTH_CONTIG_PACK,
            BATCH_TO_SPACE_MODE_HIGH_DILATION_LANE_SCATTER,
        BATCH_TO_SPACE_MODE_LIGHTWEIGHT_GENERIC,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_8,
        BATCH_TO_SPACE_MODE_BS2_ROWGROUP_PACK_16,
        BATCH_TO_SPACE_MODE_BLOCK1_CROP_ROW_CONTRACT,
        BATCH_TO_SPACE_MODE_BLOCK1_VERTICAL_CROP_CONTIG,
        BATCH_TO_SPACE_MODE_T4_BS2_MID_LANE_CONTRACT,
        BATCH_TO_SPACE_MODE_T7_C1_8X8_SMALLCROP_MC8,
        BATCH_TO_SPACE_MODE_T7_BS2_SMALLC_TINY_WIDE_OWNER,
        BATCH_TO_SPACE_MODE_T6_BS2_FP16_HIGHDEPTH_MEDIUM_ROW2,
        BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW,
        BATCH_TO_SPACE_MODE_T7_BS2_FP16_MEDIUM_NARROW_LANE,
        BATCH_TO_SPACE_MODE_T7_OUTW1_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW2_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW4_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_OUTW7_ALIGNED_ROWCONTRACT,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW1_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW2_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW3_4_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OUTW5_7_DELAY,
        BATCH_TO_SPACE_MODE_T7_BUCKET_OTHER_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B1_W3_4_ROW256_512_OUT64_128_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B2_W3_4_ROW256_512_OUT128_512_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B3_W3_4_ROW_GT512_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B4_W5_7_ROW_GT256_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B5_W1_2_ROW_GT128_PERF,
        BATCH_TO_SPACE_MODE_T9_BS4_ALIGNED_ROW_ASSEMBLE,
        BATCH_TO_SPACE_MODE_T7_OTHER_B6_ROWNARROW_OUTW_GE8_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B7_NONALIGNED_CGT16_DELAY,
        BATCH_TO_SPACE_MODE_T7_OTHER_B8_OTHER_DELAY,
        BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS2,
        BATCH_TO_SPACE_MODE_SMALLC_ROW_OWNER_BS4),
    ),
);
