#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define BTS_SCH_MODE_DIRECT 1
#define BTS_SCH_MODE_TINY_F32_ODD_CROP 2
#define BTS_SCH_MODE_DIRECT_B2_NOCROP 6
#define BTS_SCH_MODE_GATHER_B2_CROP 7
#define BTS_SCH_MODE_FIXED_B4_CROP_T09 8
#define BTS_SCH_MODE_FIXED_HALF_C4096 9
#define BTS_SCH_MODE_FIXED_F32_C64 10
#define BTS_SCH_MODE_FIXED_B2_PHASE_T10 11
#define BTS_SCH_MODE_FIXED_F32_C128_T01 12
#define BTS_SCH_MODE_F32_PLANE_INTERLEAVE 13
#define BTS_SCH_MODE_FIXED_HALF_FLAT_T07 14
#define BTS_SCH_MODE_FIXED_HALF_CROP_T05 15

#define BTS_SCH_MODE_LIST \
    BTS_SCH_MODE_DIRECT, BTS_SCH_MODE_TINY_F32_ODD_CROP, \
    BTS_SCH_MODE_DIRECT_B2_NOCROP, BTS_SCH_MODE_GATHER_B2_CROP, \
    BTS_SCH_MODE_FIXED_B4_CROP_T09, BTS_SCH_MODE_FIXED_HALF_C4096, \
    BTS_SCH_MODE_FIXED_F32_C64, BTS_SCH_MODE_FIXED_B2_PHASE_T10, \
    BTS_SCH_MODE_FIXED_F32_C128_T01, BTS_SCH_MODE_F32_PLANE_INTERLEAVE, \
    BTS_SCH_MODE_FIXED_HALF_FLAT_T07, BTS_SCH_MODE_FIXED_HALF_CROP_T05

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(schMode, 4, ASCENDC_TPL_UI_LIST, BTS_SCH_MODE_LIST),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, BTS_SCH_MODE_LIST),
    ),
);
