// TilingKey模板定义的头文件
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define BTS_TPL_GENERAL 0
#define BTS_TPL_POINT3 3
#define BTS_TPL_POINT3_TILE2 81
#define BTS_TPL_POINT3_TILE2_DB 82
#define BTS_TPL_POINT3_PHASE7 83
#define BTS_TPL_POINT3_BETA 84
#define BTS_TPL_POINT4 4
#define BTS_TPL_POINT4_BATCH 45
#define BTS_TPL_POINT4_2ROW 46
#define BTS_TPL_POINT4_UNROLL 47
#define BTS_TPL_POINT4_ROW40 48
#define BTS_TPL_POINT4_READ_CONTIG 49
#define BTS_TPL_POINT4_BETA 50
#define BTS_TPL_POINT2_BETA 56
#define BTS_TPL_POINT6 6
#define BTS_TPL_POINT6_4CORE_ROW 64
#define BTS_TPL_POINT6_16CORE 65
#define BTS_TPL_POINT7 7
#define BTS_TPL_POINT7_4CORE 76
#define BTS_TPL_POINT7_16CORE 77
#define BTS_TPL_POINT7_BETA 116
#define BTS_TPL_POINT10 110
#define BTS_TPL_POINT1 111
#define BTS_TPL_POINT1_HALF 112
#define BTS_TPL_POINT1_QUARTER 113
#define BTS_TPL_POINT5_BETA 114
#define BTS_TPL_POINT6_BETA 115
#define BTS_TPL_POINT8_BETA 117
#define BTS_TPL_POINT9_BETA 118
#define BTS_TPL_POINT10_BETA 119

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(BTS_POINT, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST,
        BTS_TPL_GENERAL, BTS_TPL_POINT3, BTS_TPL_POINT3_TILE2, BTS_TPL_POINT3_TILE2_DB,
        BTS_TPL_POINT3_PHASE7, BTS_TPL_POINT3_BETA,
        BTS_TPL_POINT4, BTS_TPL_POINT4_BATCH, BTS_TPL_POINT4_2ROW,
        BTS_TPL_POINT4_UNROLL, BTS_TPL_POINT4_ROW40, BTS_TPL_POINT4_READ_CONTIG,
        BTS_TPL_POINT4_BETA,
        BTS_TPL_POINT2_BETA,
        BTS_TPL_POINT6, BTS_TPL_POINT6_4CORE_ROW, BTS_TPL_POINT6_16CORE,
        BTS_TPL_POINT7, BTS_TPL_POINT7_4CORE, BTS_TPL_POINT7_16CORE,
        BTS_TPL_POINT10, BTS_TPL_POINT1, BTS_TPL_POINT1_HALF, BTS_TPL_POINT1_QUARTER,
        BTS_TPL_POINT5_BETA, BTS_TPL_POINT6_BETA, BTS_TPL_POINT7_BETA,
        BTS_TPL_POINT8_BETA, BTS_TPL_POINT9_BETA, BTS_TPL_POINT10_BETA),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(BTS_POINT, ASCENDC_TPL_UI_LIST,
            BTS_TPL_GENERAL, BTS_TPL_POINT3, BTS_TPL_POINT3_TILE2, BTS_TPL_POINT3_TILE2_DB,
            BTS_TPL_POINT3_PHASE7, BTS_TPL_POINT3_BETA,
            BTS_TPL_POINT4, BTS_TPL_POINT4_BATCH, BTS_TPL_POINT4_2ROW,
            BTS_TPL_POINT4_UNROLL, BTS_TPL_POINT4_ROW40, BTS_TPL_POINT4_READ_CONTIG,
            BTS_TPL_POINT4_BETA,
            BTS_TPL_POINT2_BETA,
            BTS_TPL_POINT6, BTS_TPL_POINT6_4CORE_ROW, BTS_TPL_POINT6_16CORE,
            BTS_TPL_POINT7, BTS_TPL_POINT7_4CORE, BTS_TPL_POINT7_16CORE,
            BTS_TPL_POINT10, BTS_TPL_POINT1, BTS_TPL_POINT1_HALF, BTS_TPL_POINT1_QUARTER,
            BTS_TPL_POINT5_BETA, BTS_TPL_POINT6_BETA, BTS_TPL_POINT7_BETA,
            BTS_TPL_POINT8_BETA, BTS_TPL_POINT9_BETA, BTS_TPL_POINT10_BETA),
    ),
);
