#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(Addcmul,
    ASCENDC_TPL_DATATYPE_DECL(DT_INPUT_DATA, C_DT_FLOAT16, C_DT_FLOAT, C_DT_INT8, C_DT_INT32),
    ASCENDC_TPL_UINT_DECL(ADD_CMUL_MODE, 8, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 2),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 3),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 4),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 5),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 7),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 8),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 9),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 10),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 11),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 2),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 3),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 4),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 5),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 7),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 8),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 9),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 10),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 11),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 3),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 4),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 6),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 7),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 8),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 9),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 10),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT8),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 11),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 3),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 4),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 6),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 7),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 8),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 9),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 10),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_INPUT_DATA, C_DT_INT32),
        ASCENDC_TPL_UINT_SEL(ADD_CMUL_MODE, ASCENDC_TPL_UI_LIST, 11),
    ),
);
