/*!
 * \file confusion_matrix_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __CONFUSIONMATRIX_TILING_KEY_H__
#define __CONFUSIONMATRIX_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define CONFUSIONMATRIX_TPL_SCH_MODE_0 0
#define CONFUSIONMATRIX_TPL_SCH_MODE_1 1
#define CONFUSIONMATRIX_TPL_SCH_MODE_2 2
#define CONFUSIONMATRIX_TPL_SCH_MODE_3 3
#define CONFUSIONMATRIX_TPL_SCH_MODE_4 4
#define CONFUSIONMATRIX_TPL_SCH_MODE_5 5
#define CONFUSIONMATRIX_TPL_SCH_MODE_6 6

ASCENDC_TPL_ARGS_DECL(
    ConfusionMatrix,
    ASCENDC_TPL_UINT_DECL(
        schMode,
        3,
        ASCENDC_TPL_UI_LIST,
        CONFUSIONMATRIX_TPL_SCH_MODE_0,
        CONFUSIONMATRIX_TPL_SCH_MODE_1,
        CONFUSIONMATRIX_TPL_SCH_MODE_2,
        CONFUSIONMATRIX_TPL_SCH_MODE_3,
        CONFUSIONMATRIX_TPL_SCH_MODE_4,
        CONFUSIONMATRIX_TPL_SCH_MODE_5,
        CONFUSIONMATRIX_TPL_SCH_MODE_6));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(
        schMode,
        ASCENDC_TPL_UI_LIST,
        CONFUSIONMATRIX_TPL_SCH_MODE_0,
        CONFUSIONMATRIX_TPL_SCH_MODE_1,
        CONFUSIONMATRIX_TPL_SCH_MODE_2,
        CONFUSIONMATRIX_TPL_SCH_MODE_3,
        CONFUSIONMATRIX_TPL_SCH_MODE_4,
        CONFUSIONMATRIX_TPL_SCH_MODE_5,
        CONFUSIONMATRIX_TPL_SCH_MODE_6)));

#endif
