// TilingKey模板定义的头文件
#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(BatchToSpace,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
    ASCENDC_TPL_BOOL_DECL(ROUTE_B0, 0, 1),
    ASCENDC_TPL_BOOL_DECL(ROUTE_B1, 0, 1),
    ASCENDC_TPL_BOOL_DECL(ROUTE_B2, 0, 1),
    ASCENDC_TPL_BOOL_DECL(ROUTE_B3, 0, 1),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_FLOAT),
        ASCENDC_TPL_BOOL_SEL(ROUTE_B0, 0, 1),
        ASCENDC_TPL_BOOL_SEL(ROUTE_B1, 0, 1),
        ASCENDC_TPL_BOOL_SEL(ROUTE_B2, 0, 1),
        ASCENDC_TPL_BOOL_SEL(ROUTE_B3, 0, 1),
    ),
);
