#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define ERF_SCH_MODE_SINGLE         0
#define ERF_SCH_MODE_GENERAL        1

ASCENDC_TPL_ARGS_DECL(Erf,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT),
    ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST,
        ERF_SCH_MODE_SINGLE, ERF_SCH_MODE_GENERAL),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
            ERF_SCH_MODE_SINGLE, ERF_SCH_MODE_GENERAL),
    ),
);
