#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(Lerp,
    ASCENDC_TPL_DATATYPE_DECL(DT_START, C_DT_FLOAT16, C_DT_FLOAT, ASCENDC_TPL_INPUT(0)),
    ASCENDC_TPL_UINT_DECL(LERP_MODE, 2, ASCENDC_TPL_UI_LIST, 0, 1, 2),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT16),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 2),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 1),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_START, C_DT_FLOAT),
        ASCENDC_TPL_UINT_SEL(LERP_MODE, ASCENDC_TPL_UI_LIST, 2),
    ),
);
